version: '3.9'

services:
  dev-container:
    image: anitvam/dev-container:latest
    deploy:
      placement:
        constraints:
          - node.role==manager
    environment:
      PUBLIC_KEY: ${PUBLIC_KEY}
    volumes:
      - "data:/persistent"
    ports:
      - ${PORT}:22
    working_dir: /persistent

volumes:
  data:
    name: ${VOLUME}
